name: Release a new version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'the version to be released'
        required: true

jobs:
  build:
    runs-on: ${{ matrix.os }}
    continue-on-error: true
    strategy:
      matrix:
        os: [ macos-latest, windows-latest, ubuntu-latest ]
    env:
      BUCKET_NAME: 'spb-github-test-1e4f5ff1-ee54'
      RELEASE_VERSION: ${{ github.event.inputs.version }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::391059136496:role/SpbGithubTesting
          aws-region: ap-southeast-2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      #      - name: build and test
      #        run: ./gradlew nativeTest --info
      - name: native compile
        run: ./gradlew nativeCompile --info
      - uses: actions/upload-artifact@v3
        with:
          name: spb-${{ matrix.os }}
          path: |
            build/native/nativeCompile/spb 
            build\native\nativeCompile\spb.exe


  release:
    needs: [ build ]
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: spb-macos-latest
      - uses: actions/download-artifact@v3
        with:
          name: spb-ubuntu-latest
      - uses: actions/download-artifact@v3
        with:
          name: spb-windows-latest.exe
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: |
            spb-macos-latest
            spb-ubuntu-latest
            spb-windows-latest.exe
            
