name: Release a new version
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'the version to be released'
        required: true

jobs:
  buildAndRelease:
    runs-on: macos-12
    env:
      RELEASE_VERSION: ${{ github.event.inputs.version }}
      BUCKET_NAME: 'spb-github-test-1e4f5ff1-ee54'
    permissions:
      id-token: write   # This is required for requesting the JWT
      contents: write    # This is required for actions/checkout
    steps:
      - uses: actions/checkout@v3
      - uses: gradle/wrapper-validation-action@v1
      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v1-node16
        with:
          role-to-assume: arn:aws:iam::391059136496:role/SpbGithubTesting
          aws-region: ap-southeast-2
      - uses: graalvm/setup-graalvm@v1
        with:
          version: '22.3.1'
          java-version: '19'
          components: 'native-image'
          github-token: ${{ secrets.GITHUB_TOKEN }}
          native-image-job-reports: 'true'
      #      - name: test
      #        run: ./gradlew nativeTest --info
      - name: build
        run: ./gradlew nativeCompile --info
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: build/native/nativeCompile/spb
